enum privileges
{
    PRIVILEGE_NONE,
    PRIVILEGE_CASH,  
    PRIVILEGE_BIGCASH,  
    PRIVILEGE_GRANTED,  
    PRIVILEGE_LOWMODERATOR,
    PRIVILEGE_MIDMODERATOR,
    PRIVILEGE_HIGHMODERATOR,
    PRIVILEGE_ADMINISTRATOR,
    PRIVILEGE_FOUNDER
}