enum privileges
{
    PRIVILEGE_NONE,
    PRIVILEGE_HELPER = 3,
    PRIVILEGE_LOWMODERATOR = 4,
    PRIVILEGE_MIDMODERATOR = 5,
    PRIVILEGE_HIGHMODERATOR = 6,
    PRIVILEGE_ADMINISTRATOR = 7,
    PRIVILEGE_FOUNDER = 8
}